[Interface]
PrivateKey = <REDACTED — see credentials file>
Address = 10.10.0.2/24
DNS = 192.168.56.10

[Peer]
# ztcs-perimeter — AWS EC2
PublicKey = UWA4YOZCgr/WdGIucxbn/EwwTvD7fsplw/akhBVF9yk=
Endpoint = <PERIMETER_PUBLIC_IP>:51820
AllowedIPs = 10.10.0.1/32, 10.0.0.0/16
PersistentKeepalive = 25